# Site settings
title: teknodrom
email: hello@teknodrom.cc
description: > # this means to ignore newlines until "baseurl:"
  Teknodrom is currently working on a secret.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: teknodrom
github_username:  teknodrom

# Build settings
markdown: kramdown
