# Site settings
title: teknodrom
email: hello@teknodrom.cc
description: > # this means to ignore newlines until "baseurl:"
  We are currently working on top secret awesomeness. Follow us on Twitter and keep visiting our website for rad updates!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: helloteknodrom
github_username:  teknodrom
team_members: [{name: "Jesper", email: "jesper@teknodrom.cc"}, "Christian", "Oscar"]

# Build settings
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock, .gitignore]
